swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /fermlog

# Paths supported by the server application
paths:
  /{system_name}/sensors:
    get:
      operationId: sensors.get_all
      responses:
        200:
          description: Success

